export enum ProfileType {
  STANDARD = 'STANDARD',
  BETA = 'BETA',
  DEADMAN = 'DEADMAN',
  PVP_ARENA = 'PVP_ARENA',
  SHATTERED_RELICS_LEAGUE = 'SHATTERED_RELICS_LEAGUE',
  TRAILBLAZER_RELOADED_LEAGUE = 'TRAILBLAZER_RELOADED_LEAGUE',
}

export enum AllowedProfileType {
  STANDARD = 'STANDARD',
  DEADMAN = 'DEADMAN',
  TRAILBLAZER_RELOADED_LEAGUE = 'TRAILBLAZER_RELOADED_LEAGUE',
}
