export enum ProfileType {
  STANDARD = 'STANDARD',
  BETA = 'BETA',
  DEADMAN = 'DEADMAN',
  PVP_ARENA = 'PVP_ARENA',
  SHATTERED_RELICS_LEAGUE = 'SHATTERED_RELICS_LEAGUE',
  TRAILBLAZER_RELOADED_LEAGUE = 'TRAILBLAZER_RELOADED_LEAGUE',
  RAGING_ECHOES_LEAGUE = 'RAGING_ECHOES_LEAGUE',
  GRID_MASTER = 'GRID_MASTER',
}

export enum AllowedProfileType {
  STANDARD = 'STANDARD',
}
