name: Regenerate data from cache
on:
    push:
        branches:
            '*'
    schedule:
        - cron: '30 13 * * *'

jobs:
    regenerate-data:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: pwd